# coding: utf-8

"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.create_channel_dto import CreateChannelDto  # noqa: E501
from swagger_client.rest import ApiException


class TestCreateChannelDto(unittest.TestCase):
    """CreateChannelDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCreateChannelDto(self):
        """Test CreateChannelDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.create_channel_dto.CreateChannelDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
