# coding: utf-8

"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response200_info import InlineResponse200Info  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse200Info(unittest.TestCase):
    """InlineResponse200Info unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200Info(self):
        """Test InlineResponse200Info"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response200_info.InlineResponse200Info()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
