# coding: utf-8

"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dsb_client.swagger_client
from dsb_client.swagger_client.models.inline_response503 import InlineResponse503  # noqa: E501
from dsb_client.swagger_client.rest import ApiException


class TestInlineResponse503(unittest.TestCase):
    """InlineResponse503 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse503(self):
        """Test InlineResponse503"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response503.InlineResponse503()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
