# coding: utf-8

"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.message_api import MessageApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMessageApi(unittest.TestCase):
    """MessageApi unit test stubs"""

    def setUp(self):
        self.api = MessageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_message_controller_get_new_from_channel(self):
        """Test case for message_controller_get_new_from_channel

        """
        pass

    def test_message_controller_publish(self):
        """Test case for message_controller_publish

        """
        pass


if __name__ == '__main__':
    unittest.main()
