# coding: utf-8

"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import dsb_client.swagger_client
from dsb_client.swagger_client.models.publish_message_dto import PublishMessageDto  # noqa: E501
from dsb_client.swagger_client.rest import ApiException


class TestPublishMessageDto(unittest.TestCase):
    """PublishMessageDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPublishMessageDto(self):
        """Test PublishMessageDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.publish_message_dto.PublishMessageDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
