# coding: utf-8

"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.message_dto import MessageDTO  # noqa: E501
from swagger_client.rest import ApiException


class TestMessageDTO(unittest.TestCase):
    """MessageDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMessageDTO(self):
        """Test MessageDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.message_dto.MessageDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
