# coding: utf-8

"""
    DSB Message Broker API

    Swagger documentation for the DSB Message Broker API  # noqa: E501

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MessageDTO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'payload': 'str',
        'sender': 'str',
        'signature': 'str'
    }

    attribute_map = {
        'id': 'id',
        'payload': 'payload',
        'sender': 'sender',
        'signature': 'signature'
    }

    def __init__(self, id=None, payload=None, sender=None, signature=None):  # noqa: E501
        """MessageDTO - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._payload = None
        self._sender = None
        self._signature = None
        self.discriminator = None
        self.id = id
        self.payload = payload
        self.sender = sender
        self.signature = signature

    @property
    def id(self):
        """Gets the id of this MessageDTO.  # noqa: E501

        Message id  # noqa: E501

        :return: The id of this MessageDTO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this MessageDTO.

        Message id  # noqa: E501

        :param id: The id of this MessageDTO.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def payload(self):
        """Gets the payload of this MessageDTO.  # noqa: E501

        Any stringified payload like JSON, BASE64 etc  # noqa: E501

        :return: The payload of this MessageDTO.  # noqa: E501
        :rtype: str
        """
        return self._payload

    @payload.setter
    def payload(self, payload):
        """Sets the payload of this MessageDTO.

        Any stringified payload like JSON, BASE64 etc  # noqa: E501

        :param payload: The payload of this MessageDTO.  # noqa: E501
        :type: str
        """
        if payload is None:
            raise ValueError("Invalid value for `payload`, must not be `None`")  # noqa: E501

        self._payload = payload

    @property
    def sender(self):
        """Gets the sender of this MessageDTO.  # noqa: E501

        Sender of the message  # noqa: E501

        :return: The sender of this MessageDTO.  # noqa: E501
        :rtype: str
        """
        return self._sender

    @sender.setter
    def sender(self, sender):
        """Sets the sender of this MessageDTO.

        Sender of the message  # noqa: E501

        :param sender: The sender of this MessageDTO.  # noqa: E501
        :type: str
        """
        if sender is None:
            raise ValueError("Invalid value for `sender`, must not be `None`")  # noqa: E501

        self._sender = sender

    @property
    def signature(self):
        """Gets the signature of this MessageDTO.  # noqa: E501

        Compacted EcdsaSecp256k1Signature2019  # noqa: E501

        :return: The signature of this MessageDTO.  # noqa: E501
        :rtype: str
        """
        return self._signature

    @signature.setter
    def signature(self, signature):
        """Sets the signature of this MessageDTO.

        Compacted EcdsaSecp256k1Signature2019  # noqa: E501

        :param signature: The signature of this MessageDTO.  # noqa: E501
        :type: str
        """
        if signature is None:
            raise ValueError("Invalid value for `signature`, must not be `None`")  # noqa: E501

        self._signature = signature

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MessageDTO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MessageDTO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
